// 定义数据库中的枚举，因为js不支持枚举，故使用对象模拟枚举
// 题目类型枚举
export const QuestionType = {
  SINGLE_CHOICE: 'SINGLE_CHOICE',
  MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
  JUDGMENT: 'JUDGMENT',
  FILL_BLANK: 'FILL_BLANK',
  CALCULATION: 'CALCULATION',
  SHORT_ANSWER: 'SHORT_ANSWER',
}
//难度等级
export const QuestionLevel = {
  EASY: 'EASY',
  MEDIUM: 'MEDIUM',
  HARD: 'HARD',
}
// 知识点分类
export const KnowledgeUnit = {
  PROBABILITY_BASE: 'PROBABILITY_BASE',
  RANDOM_VARIABLE: 'RANDOM_VARIABLE',
  DIGITAL_CHARACTER: 'DIGITAL_CHARACTER',
  LARGE_NUMBER_LAW: 'LARGE_NUMBER_LAW',
  MATHEMATICAL_STAT: 'MATHEMATICAL_STAT',
  POINT_ESTIMATION: 'POINT_ESTIMATION',
  HYPOTHESIS_TEST: 'HYPOTHESIS_TEST',
}
